<?php

function extractSeriesName($data) {
    $serieNamePamesa=pamesaSerieList($data);
    if($serieNamePamesa){
        return $serieNamePamesa;
    }else{
        $serieNameOut=getMappingValue($data);
         if($serieNameOut){
            return $serieNameOut;
         }else{
             return'404 Error'.$data;
         }
    }
}


function pamesaSerieList($data){
    $seriesList = [
       'ACQUILEA',
       'ADAIR',
       'ALBION',
       'ALLOY',
       'AMARNA',
       'ANZA',
       'APULIA',
       'ARDESIA',
       'AREZZO',
       'ARGILE',
       'AROA',
       'ART',
       'ART-CASSATT',
       'ART-CEZZANE',
       'ART-COROT',
       'ART-DEGAS',
       'ART-GAUGUIN',
       'ARTISAN',
       'ART-LEPIC',
       'ARTLINE-ARTSQUARE',
       'ART-MONET',
       'ART-RENOIR',
       'ART-RODIN',
       'ART-SEURAT',
       'ART-SIGNAC',
       'ART-SYSLEY',
       'ASCOLANO',
       'ASTRALE',
       'AT.ACADIAN',
       'AT.AIRE',
       'AT.ALCORA',
       'AT.ALHAMBRA',
       'AT.ALPHA',
       'AT.ALPHA-AT.ALPHA BEAT PORCELANICO',
       'AT.ALPI',
       'AT.ANDROS',
       'AT.AREN',
       'AT.ATTAS',
       'AT.BADEM',
       'AT.BAHIA',
       'AT.BARBADOS',
       'AT.BASIC',
       'AT.BERMUDAS',
       'AT.BLANCO-BYBLOS-EGEO',
       'AT.BLANCO-DUNA-VIGGO',
       'AT.BLANCOS 36X80',
       'AT.BLAZE',
       'AT.BOI',
       'AT.BOREAL',
       'AT.BRILLO-MATE',
       'AT.BRITANIA',
       'AT.BURLINGSTONE',
       'AT.BURMA',
       'AT.CARSON',
       'AT.CEYLON',
       'AT.CHAMBORD',
       'AT.CHOICE',
       'AT.CHOICE PASTA ROJA',
       'AT.CLASSIC',
       'AT.DAIN',
       'AT.DAKOTA',
       'AT.DEMOS',
       'AT.DENVER',
       'AT.EDGE',
       'AT.EIFFEL',
       'AT.ELITE',
       'AT.ENTIS',
       'AT.ESCOCIA',
       'AT.EVOQUE',
       'AT.FORALL',
       'AT.GAIA',
       'AT.GALES',
       'AT.HARO',
       'AT.INCONTRO',
       'AT.KIEL',
       'AT.KILBURN-WATERLOO',
       'AT.LEGNO',
       'AT.LEGNO PASTA ROJA',
       'AT.LOFT',
       'AT.LOUVRE',
       'AT.LUBECK',
       'AT.MARTE',
       'AT.MIST',
       'AT.MUREN',
       'AT.MUSEUM',
       'AT.MYLO',
       'AT.NAZA',
       'AT.NAZA PASTA ROJA',
       'AT.NITID-AT.NAMUR',
       'AT.PALMA',
       'AT.PIREO',
       'AT.POMPEI',
       'AT.PORTOFINO',
       'AT.PORTOFINO PASTA ROJA',
       'AT.RAINIER',
       'AT.REVAL',
       'AT.RIGA',
       'AT.RIMINI PASTA ROJA',
       'AT.SALEM',
       'AT.SIGMA-RVTO',
       'AT.TABOR',
       'AT.TEIDE',
       'AT.THULE',
       'AT.TIAD',
       'AT.TITAN',
       'AT.TRENT',
       'AT.TRENT-AT.RLV.TRENT',
       'AT.URBEX',
       'AT.VERSILIA',
       'AT.VIGGO',
       'BELVEDERE',
       'BLOCK',
       'BOGART',
       'BOIS',
       'BOSQUE',
       'BRICKWALL',
       'BRIENZ 20X60',
       'CALACATA GOLD',
       'CALACATA GOLD PASTA BLANCA',
       'CALACATA WHITE',
       'CALACATA WHITE PASTA BLANCA',
       'CASTELLO',
       'CASTLE',
       'CELLINI',
       'CELLINI-PASTA-BLANCA',
       'CIVIS',
       'CONCRET',
       'CORALSTONE',
       'CREMA MARFIL',
       'CRETA',
       'CROMAT',
       'CROMAT PASTA BLANCA',
       'CRYSTAL WHITE',
       'DANELLO',
       'DECO',
       'DESERT',
       'DESERT-PASTA-BLANCA',
       'DIAGONALS-DIAMOND',
       'DOLOMITE',
       'DORIA',
       'DORSET',
       'DOSSO',
       'DREAM',
       'DUPLOCEM',
       'DUPLOSTONE',
       'EATON',
       'ELEGANZA',
       'ELEGANZA PASTA BLANCA',
       'EMPOLI-SENESI',
       'EOS',
       'ERDING',
       'ESSEN',
       'ESSENZA',
       'ESSENZA-PASTA-BLANCA',
       'ESSENZA RELIEVE',
       'ETERNITY',
       'ETNA',
       'FENIX',
       'FIUME',
       'FRONDA',
       'GELSA',
       'GOLDEN CROMAT',
       'GRANSASSO',
       'GRAVEL',
       'GREENPARK',
       'GROVE',
       'HAZEL',
       'HERMES',
       'ILCOTTO',
       'IMPERIUM',
       'INZA',
       'IRIDA',
       'KALON',
       'KEDIRI',
       'KENYA',
       'KENZO',
       'KINGSWOOD',
       'KONCEPT',
       'KONCEPT PASTA BLANCA',
       'KRONO',
       'LEMNOS',
       'LENCI',
       'LIFEFULL',
       'LIN',
       'LINCOLN',
       'LOWRY',
       'LUCCA',
       'LUNI',
       'LUX DANAE',
       'LUX DEVA',
       'LUX EUPHORIA',
       'LUX ICEBERG',
       'LUX JATOBA',
       'LUX KIONIA',
       'LUX LAURANTS',
       'LUX NOOR',
       'LUX VIOLA',
       'MAGMA',
       'MALLAS',
       'MANAOS',
       'METAL',
       'MIDWAY',
       'MIDWAY PASTA BLANCA',
       'MOLEANOS',
       'MONTEBIANCO',
       'MONTPELLIER',
       'MOSEL',
       'MURANO',
       'MURANO REVESTIMIENTO',
       'NASO',
       'NEBULA',
       'NERA',
       'ODEON PASTA BLANCA',
       'OKAI',
       'OLDMANOR',
       'OMNIA',
       'ONIX',
       'ORIGIN ALLOY',
       'ORIGIN AUREA',
       'ORIGIN ELEGANZA',
       'ORIGIN FEEL',
       'ORIGIN GRACE',
       'ORIGIN MAYFAIR',
       'ORIGIN MAYOLICA',
       'ORIGIN OLDMANOR',
       'ORIGIN ROVERE',
       'ORIGIN SLATE WAY',
       'ORIGIN SUBWAY',
       'ORIGIN TORANO',
       'ORIGIN TOSCANA',
       'PATAGONIA',
       'PIETRA DI GRE',
       'PIETRA DI LAVAGNA',
       'PIETRA DI MARMI',
       'PIETRA DI MARMI PASTA BLANCA',
       'PIETRA DI MERANO',
       'PIETRA DI RAPOLANO',
       'PINE WOOD',
       'PISA',
       'PLAIN',
       'PORTLANDSTONE',
       'POTSDAM',
       'PRINCE',
       'PROVENZA',
       'PROVENZAL',
       'REGAL',
       'RHIN',
       'RLV.GHAT',
       'RLV-NERA-PASTA-BLANCA',
       'ROCKSTONE',
       'ROMA BLUE',
       'ROVERE',
       'ROVERE-PASTA-BLANCA',
       'RUSTY METAL',
       'SARDONYX',
       'SENSE',
       'SILKSTONE',
       'SILS',
       'SLATE WAY',
       'SOSPIRO',
       'SOULAND',
       'SOUL-WABE',
       'STYLE',
       'SV.HIERRO',
       'TAJ MAHAL',
       'TAO COLLECTION',
       'TAVIRA',
       'TENDENZA',
       'TERRAZZO',
       'TORANO',
       'TORANO_PASTA_BLANCA',
       'TOVAR',
       'TREND-COLLECTION',
       'TREND-COLLECTION-ROYAL-TREND',
       'TRESANA',
       'URBANA',
       'VERONA',
       'VINTAGE',
       'VITA',
       'VITA PASTA BLANCA',
       'WALNUT',
       'WELLS',
       'WHITEHALL',
       'WHITES-ALASKA-TORONTO',
       'WHITES-TRIPOLI',
       'ZEN COLLECTION'
    ];

    // Convert input to uppercase for case-insensitive comparison
    $data = strtoupper($data);

    foreach ($seriesList as $serie) {
        if (strpos($data, $serie) !== false) {
            return ucwords(strtolower($serie));
        }
    }
    return null;
}


function getMappingValue($searchString) {
    $mappings = [
       'CALACATA GOLD' =>'CALACATA GOLD',
       'PIETRA DI BIANCO' =>'PIETRA DI GRE',
       'PIETRA DI CREMA' =>'PIETRA DI GRE',
       'PIETRA DI GRIGIO' =>'PIETRA DI GRE',
       'PIETRA DI MULTI' =>'PIETRA DI GRE',
       'PIETRA DI PERLA' =>'PIETRA DI GRE',
       'AT.EXT.ALPHA' =>'AT.ALPHA',
       'RAPOLANO' =>'PIETRA DI RAPOLANO',
       'CR.NOOR WHITE' =>'LUX NOOR',
       'MAYFAIR' =>'ORIGIN MAYFAIR',
       'MARMI PIETRA' =>'PIETRA DI MARMI',
       'WHITE CALACATA 1.' =>'CALACATA WHITE',
       'LUX.EUPHORIA GREEN' =>'LUX EUPHORIA',
       'ROMA BLUE' =>'ROMA BLUE',
       'CONCA BIANCO' =>'CONCA',
       'CONCA GREIGE' =>'CONCA',
       'CONCA PERLA' =>'CONCA',
       'CR.NOOR WHITE' =>'MALLAS',
       'GRE PIETRA DI GRIGIO' =>'PIETRA DI GRE',
       'GRE PIETRA DI MULTI' =>'PIETRA DI GRE',
       'GRE PIETRA DI PERLA' =>'PIETRA DI LAVAGNA',
       'LAVAGNA PIETRA DI ARGENTO' =>'PIETRA DI LAVAGNA',
       'LAVAGNA PIETRA DI GRIGIO' =>'PIETRA DI LAVAGNA',
       'LAVAGNA PIETRA DI PERLA' =>'PIETRA DI LAVAGNA',
       'LAVAGNA PIETRA DI SABBIA' =>'LAVAGNA PIETRA DI SABBIA',
       'MONREALE GRIGIO' =>'MONREALE',
       'MONREALE PERLA' =>'MONREALE',
       'MONREALE SABBIA' =>'MONREALE',
       'MONREALE TAUPE' =>'MONREALE',
       'TRIPOLI BLANCO' =>'WHITES-TRIPOLI',
       'TRIPOLI MATE SNOW' =>'WHITES-TRIPOLI',
       'DEC.ODEON BEIGE' =>'ODEON PASTA BLANCA',
       'DEC.ODEON GRIS' =>'ODEON PASTA BLANCA',
       'ODEON BLANCO' =>'ODEON PASTA BLANCA',
       'ODEON MARFIL' =>'ODEON PASTA BLANCA',
       'RLV.LACIO 1.' =>'CALACATA GOLD PASTA BLANCA',
       'RLV.ODEON BLANCO' =>'ODEON PASTA BLANCA',
       'RLV.ODEON MARFIL' =>'ODEON PASTA BLANCA',
       'TRIPOLI BLANCO' =>'WHITES TRIPOLI',
       'TRIPOLI MATE SNOW' =>'WHITES TRIPOLI',
       'WHITE CALACATA BRILLO' =>'CALACATA WHITE PASTA BLANCA',
       'AUREA' =>'ORIGIN AUREA',
       'GRACE' =>'ORIGIN GRACE',
       'MAYOLICA' =>'ORIGIN MAYOLICA', 
       'WHITE CALACATA MATE' =>'CALACATA WHITE'
    ];
    
    // Clean and extract product name
    $searchString = trim(strtoupper($searchString));
    $productName ='';
    
    // Remove dimensions and code
    if (preg_match('/\d+X\d+\s*\([A-Z]\)\s*(.+)/', $searchString, $matches)) {
        $productName = trim($matches[1]);
    } else {
        $productName = $searchString;
    }
    
    // Direct match
    if (isset($mappings[$productName])) {
        return $mappings[$productName];
    }
    
    // Check if any mapping key is contained within the product name
    foreach ($mappings as $key => $value) {
        if (strpos($productName, $key) !== false) {
            return ucwords(strtolower($value));
        }
    }
    
    return null;
}

add_shortcode('san_info_box','custom_info_box_shortcode');

function custom_info_box_shortcode($data){
    
    $result=extractSeriesName($data['id']);
    if($result){
        return  $result;
    }else{
        return "Error 404".$data['id'];
    }
}